### ISSUE TITLE
possible memory leaky

### ISSUE THREAD

**Issue by yuto3o** [symbolic-kg/PyClause#5]
Hello, PyClause is a useful tool for rule learning. Thank you for your contributions !

I find a possible memory leaky problem.

```
# define data & rules & queries
rules, status = [...], [...]
queries = [...]

opts = Options()

loader = Loader(options=opts.get("loader"))
loader.load_data(data)
loader.load_rules(rules=rules, stats=stats)

qa = QAHandler(options=opts.get("qa_handler"))

qa.calculate_answers(queries=queries, loader=loader, direction="tail")
qa.get_answers(as_string=True)
```

The above code works fine with low Memory needs (I have 32G Memory). But when I want to calculate answers one by one, like that

```
# define data & rules & queries
rules, status = [...], [...]
queries = [...]

opts = Options()

loader = Loader(options=opts.get("loader"))
loader.load_data(data)
loader.load_rules(rules=rules, stats=stats)

qa = QAHandler(options=opts.get("qa_handler"))

for query in queries:
    qa.calculate_answers(queries=[query ], loader=loader, direction="tail")
    qa.get_answers(as_string=True)[0]
```

I get an out-of-memory error. Could you give me any suggestions?

**Comment by Nzteb** [comment]
Hi,
it is at least expected that it is not effective to perform query answering one by one. You can alternatively calculate the answers for all queries once (or in batches) and iterate over them, which will give you the same result. Similar to your first example.

```
# define data & rules & queries
rules, stats = [...], [...]
queries = [...]

opts = Options()

loader = Loader(options=opts.get("loader"))
loader.load_data(data)
loader.load_rules(rules=rules, stats=stats)

qa = QAHandler(options=opts.get("qa_handler"))

qa.calculate_answers(queries=queries, loader=loader, direction="tail")
answers = qa.get_answers(as_string=True)
for i in range(len(answers)):
  query=queries[i]
   # list of candidates+scores for query i
  candidates = answers[i]

```
Could you provide a complete running example (and mention the used dataset) so we can try to reproduce?

**Comment by yuto3o** [comment]
Q&A one by one is very useful for the situation if each query has its own rules rather than sharing rules across the KG.
So that the rules need to be reloaded for each query.

```
for query in queries:
    loader.load_rules(rules=rules, stats=stats)
    qa.calculate_answers(queries=[query], loader=loader, direction="tail")
    qa.get_answers(as_string=True)[0]
```

FB15k237 and rules mined by the AnyBURL system are used in my experiment.

**Comment by Nzteb** [comment]
I could reproduce the problem, thanks! I just pushed a fix which resolved. Could you tell me if you encounter further problems?  @nomisto could you have a look, too?

**Comment by yuto3o** [comment]
ok, thanks :)
